# This file is deprecated - see jekyll-deploy.yml
name: [DEPRECATED] Jekyll to GitHub Pages

on:
  # This workflow is kept for reference only and disabled
  workflow_dispatch:
    inputs:
      confirm:
        description: 'This workflow is deprecated. Use jekyll-deploy.yml instead.'
        required: true
        default: 'no'

jobs:
  notice:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecation Notice
        run: |
          echo "This workflow is deprecated. Please use jekyll-deploy.yml instead."
          exit 1