name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      
      # Use GitHub Deploy Action to build and deploy to GitHub
      - uses: jeffreytse/jekyll-deploy-action@master
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'       # Default is gh-pages for github provider
          jekyll_src: './'         # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          cname: ''                # Default is to not use a cname
          actor: ''                # Default is the GITHUB_ACTOR
          pre_build_commands: ''   # Commands to run before build
