name: Manual Post Generation

on:
  workflow_dispatch:
    inputs:
      topic_override:
        description: 'Override random topic selection (optional)'
        required: false
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
      
      - name: Generate blog post
        run: python scripts/generate_post.py
        env:
          TOPIC_OVERRIDE: ${{ github.event.inputs.topic_override }}
      
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Add manually triggered blog post"
          git push
